### ISSUE TITLE
Donate Button URL Issue

### ISSUE THREAD

**Issue by antoniojdcarvalho** [saenzramiro/rambox#1794] opened 2018-07-30 08:33 UTC
When Donate button is clicked:
![image](https://user-images.githubusercontent.com/41895466/43386425-7d1c5742-93db-11e8-8b5a-fc177aadaf84.png)

We are redirected to a 404 web page:
![image](https://user-images.githubusercontent.com/41895466/43386449-89a9981c-93db-11e8-9df4-027155719968.png)

Cheers!

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.17134

**Comment by Ash258** [comment] 2018-07-30 08:43
Duplicate of #1749

**Comment by Ash258** [comment] 2018-07-30 08:43
Fixed in #1782

**Closed by Ash258** 2018-07-30 08:43 UTC
