### ISSUE TITLE
White Page

### ISSUE THREAD

**Issue by ComiR** [saenzramiro/rambox#181] opened 2016-08-03 07:31 UTC
With version `0.4.1` a bug was introduced. All my Mattermost tabs only display a white page. Version `0.4.0` worked fine.

```
Version: 0.4.1
Platform: win32 (x64)
Electron: 1.3.1
Chromium: 52.0.2743.82
Node: 6.3.0
```
I tried it with two unrelated servers running Mattermost `3.0.0` and `3.2.0`. The login page will show, but the chat interface won't.

**Comment by matiasgagliano** [comment] 2016-08-03 13:43
Had the same experience with Gitter. It's still an issue but I was able to solve it. 

Initially Gitter's tab showed a blank page from the start, solved it by closing and reopening Rambox which now showed the login page. After every login attempt it went blank again but it got fixed after removing and re creating Gitters tab which now allows me to login. Hope it helps.

> Version: 0.4.1
> Platform: linux (x64)
> Electron: 1.3.1
> Chromium: 52.0.2743.82
> Node: 6.3.0

**Comment by saenzramiro** [comment] 2016-08-03 16:33
Yes, this is an Electron bug.

Another possible solution is this:

1. On blank screen, go to the Mattermost tab and double click and select Dev Tools.
2. Go to Network tab and hit F5 on your keyboard.

Works?

**Comment by blasmat** [comment] 2016-08-03 18:22
I am having this issue in version 0.4.1 with MightyText, Hangouts, and Inbox.  All worked properly in 0.4.0.  Saenzramiro's suggestion does not resolve the issue.  

If I start clicking and dragging within the MightyText or Hangouts tabs, I can see that I am dragging a gray image with the text "One account. All of Google. Sign in with your Google account."  

This Google login screen appeared properly in Inbox, but once I signed in I get a white screen.  If I click and drag around in the Inbox tab, I can see that I am dragging a translucent image of the page I would expect to see (the emails sitting in my inbox, etc.).

Version: 0.4.1
Platform: linux (x64)
Electron: 1.3.1
Chromium: 52.0.2743.82
Node: 6.3.0

**Comment by saenzramiro** [comment] 2016-08-03 18:30
Guys, I just found that is an Electron bug in version 1.3.1. See here: electron/electron/pull/6646

In version 1.3.2 they fixed it. See here: https://github.com/electron/electron/releases/tag/v1.3.2

So for next version I will update to the latest version of Electron and then, should work.

**Comment by gcasanova** [comment] 2016-09-09 07:44
This issue still happens, not only Mattermost, it will happen for other services as well (eg. Facebook Messenger). My Rambox installation details,

Version: 0.4.2
Platform: linux (x64)
Electron: 1.3.4
Chromium: 52.0.2743.82
Node: 6.3.0

PS: I've tried refreshing the page as suggested above, did not work.

**Comment by saenzramiro** [comment] 2016-09-09 12:43
@gcasanova Are other services working?

**Comment by brad** [comment] 2016-09-09 14:07
:disappointed: I am also still experiencing the "white page" bug, on Facbook Messenger and any service where page changes don't happen via AJAX. Same exact installation details as @gcasanova

**Comment by gcasanova** [comment] 2016-09-09 16:47
@saenzramiro I have only used Facebook Messenger, Mattermost, WhatsApp and Skype. The white page bug happens on both Facebook Messenger and Mattermost, the other two do work perfectly.

**Comment by jbbr** [comment] 2016-09-09 22:42
I just added Facebook Messenger and a Mattermost installation with valid SSL-certificate (Let's encrypt) without any obvious issues (Not white page).

> Rambox 0.4.2
> Arch Linux (x64)
> Electron 1.3.4... (binary from github releases/AUR)

As Mattermost is a self hosted service: Do you have a valid SSL certificate? Have you tried adding Mattermost as a custom service with check at "Trust invalid authority certificates"?

**Comment by ComiR** [comment] 2016-09-10 13:34
On this PC I'm also still getting the white page bug (with two different Mattermost instances, both SSL, one Let's Encrypt, one StartCom).
```
Version: 0.4.2
Platform: win32 (x64)
Electron: 1.3.5
Chromium: 52.0.2743.82
Node: 6.3.0
```
[The sync bug I mentioned on [Gitter](https://gitter.im/saenzramiro/rambox) (probably the same as #313) didn't happen here - I'll try that again on monday]

**Comment by gcasanova** [comment] 2016-09-12 15:45
Hangouts too :(

**Comment by blasmat** [comment] 2016-09-12 19:01
I am still having this issue as well, and it has now begun affecting Skype.  Previously, only Hangouts and MightyText were affected for me.

Worth noting:  this issue now only occurs on one of my machines, which is running Manjaro GNOME.  The issue has been resolved on two other machines running Antergos GNOME and Ubuntu 16.04 respectively.

```
Version: 0.4.2
Platform: linux (x64)
Electron: 1.3.4
Chromium: 52.0.2743.82
Node: 6.3.0
```

**Comment by brad** [comment] 2016-09-13 19:26
Now that is strange. I am running Antergos GNOME as well with the exact same versions of those items and I am seeing the white screens. There must be another problematic factor? Video card? This is mine:
`01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Venus XT [Radeon HD 8870M / R9 M270X/M370X] (rev 83)`
I'm using the `xf86-video-ati` driver

**Comment by blasmat** [comment] 2016-09-13 19:50
Manjaro machine:  `00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Kabini [Radeon HD 8330E]` running `radeon` driver.

Antergos machine:  `Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])` running `i915` driver.

Ubuntu machine:  `VGA compatible controller: Intel Corporation Sky Lake Integrated Graphics (rev 06) (prog-if 00 [VGA controller])` running `i915_bpo`

**Comment by brad** [comment] 2016-09-13 21:04
Ah HA! Starting the app with `rambox --disable-gpu` fixes all my "white page" accounts!

**Comment by saenzramiro** [comment] 2016-09-14 02:55
Can anyone try what @brad share?

If that's the problem, I can add the following lines in the app config file:

```javascript
if (process.platform === 'linux') {
    app.disableHardwareAcceleration();
}
```

**Comment by jurgenhaas** [comment] 2016-09-14 06:13
It doesn't work for me, unfortunately. But I'm not sure it takes those cli parameteres at all. First of all, my executable is `Rambox` with an uppercase R to start with and I tried providing any sort of parameters which are all taken silently. Normally an applications is complaining if you provide unsupported parameters.

**Comment by blasmat** [comment] 2016-09-14 12:51
Brad's approach worked for me.

**Comment by gcasanova** [comment] 2016-09-14 14:31
It did work for me too!

**Comment by saenzramiro** [comment] 2016-09-14 16:48
Great news! Ok, I will add this fix in next release.

**Comment by jbbr** [comment] 2016-09-15 01:29
Good to know that this is probably caused by hardware acceleration - but as me any others don't have problems with it, could you add this as a flag to the settings?

I'd like to not loose GPU-acceleration as it's working fine with Intel graphic drivers for me.

Thanks in advance

**Comment by saenzramiro** [comment] 2016-09-15 12:57
@jbbr Sure. 😉

**Closed** 2016-09-23 13:56 UTC
Labels: bug, investigate, need-community-help
