### ISSUE TITLE
Microsoft Teams not recognizing rambox

### ISSUE THREAD

**Issue by MJae** [saenzramiro/rambox#1376] opened 2018-01-05 09:07 UTC
### Steps to reproduce

1. Add Microsoft Teams
2. Sign in

### Expected behavior

It is supposed to show the app.

### Actual behavior

But I get this: https://gyazo.com/b408501ceb17f90a73685793125d5730.

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Windows 10

> Arch: x64

**Comment by valvin1** [comment] 2018-01-05 09:14
Duplicate of #1354

**Closed** 2018-01-05 15:30 UTC
