### ISSUE TITLE
Request - Feature - Notification for Win 10 Notification center

### ISSUE THREAD

**Issue by Stele77** [saenzramiro/rambox#269] opened 2016-08-27 20:39 UTC
Hi again!
AFAIK the notifications on my Win 10 RS1 system are not integrated into the notification center... In fact, there are no notifications at all, other then the small red unread counter on the logo of a service.

With Win10 now gaining a quite high user base, and with Rambox being a modern and progressive App, it would be an extremely important, even essential feature for all Win10 users, that there are notifications, and that they are integrated into the new notification center. 

AFAIK only Store Apps have native access to it. But just like Evernote is doing ATM, you could use a wrapper to convert Rambox into a Store app, without the hassle of coding a seperate version. 
A store app may seem useless, looking at windows mobile. But with Win10 Redstone 1 and 2-1 Laptops and Surface Books ect., the times are changing, and many devs now are activily working on wrapping their desktop apps for the store..
Here more infos: http://goo.gl/NnzouM

Thanks for any feedback in advance!
Steven

EDIT: The Project for wrapping Desktop Apps to UWP is named: "Project Centennial". Hope this can help!

**Comment by saenzramiro** [comment] 2016-08-28 06:28
Related #151 

Thank you for all the info. I will take a look on this.

**Comment by Mumrau** [comment] 2016-08-28 09:15
I'm not sure that you need to get inside the Windows Store in order to put notifications in notification center.
I already got quite a few softwares that displays information inside and are not on the store (Razer Synapse, Battle.net ...).
I'm not sure how this will help as I didn't look deeply inside the mechnanics of the center but still telling it :)
Regards!

**Comment by saenzramiro** [comment] 2016-08-29 22:47
Well... I think is an Electron bug because in my case, notifications displays in the Action Center but just for a few seconds (Win 10 x64).

**Comment by notnsane** [comment] 2016-08-30 02:33
I can confirm that system native notifications are working correctly in Windows 10.

I also previously requested a UWP app but it wasn't marked as a top priority (honestly, it shouldn't, Rambox is working fine as it is)

**Comment by saenzramiro** [comment] 2016-11-24 20:29
Let's merge this with #479.

**Closed by saenzramiro** 2016-11-24 20:29 UTC
Labels: feature request, investigate, windows
