### ISSUE TITLE
Restore configuration from backup creates duplicate tabs

### ISSUE THREAD

**Issue by MurzNN** [saenzramiro/rambox#1760] opened 2018-07-08 18:54 UTC
When I use `Synchronize Configuration » Restore` action - Rambox creates duplicate of current tabs, with same name but empty user data (no cookies).

How can I prevent creating duplicates on restore configuration action and make Rambox reuse already exist tabs on current device?

**Comment by MurzNN** [comment] 2018-07-08 18:56
In `~/.config/Rambox/Partitions` folder I see that duplicates have same oauth id (`servicename_N_google-oauth2%7C107098834222066052600`), but different number (`N`).

**Comment by MurzNN** [comment] 2018-07-08 18:58
If I remove all Rambox configuration (whole folder in config) and try to restore from backup, it creates tabs normally, without duplicates.

**Comment by Ash258** [comment] 2018-07-08 19:30
Duplicate of #1311

**Closed by Ash258** 2018-07-08 19:30 UTC
