### ISSUE TITLE
MS Teams broken

### ISSUE THREAD

**Issue by vTide** [saenzramiro/rambox#1366] opened 2017-12-20 08:04 UTC
Microsoft Teams does not work in this version of Rambox anymore.  It complains with "your browser version ins't supported..."

Tx!

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> darwin x64 17.0.0

**Comment by Ash258** [comment] 2017-12-21 17:14
Duplicate of #1354

**Closed** 2017-12-26 17:32 UTC
