### ISSUE TITLE
Can't login with my password

### ISSUE THREAD

**Issue by dominhduc** [saenzramiro/rambox#1718] opened 2018-06-14 13:00 UTC
I've used my password but can't login. I tried to change the password, and it went successfully. However, I tried to use the new password but it doesn't log me in. Please give me further instructions!

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.17134

**Comment by Ash258** [comment] 2018-06-14 13:34
Login where? What? How? What service?

**Comment by allstarleb** [comment] 2018-06-15 11:36
I have the same problem! Here's the screenshot - https://i.imgur.com/6VKdXui.png
i have reset it multiple times, still can't log in! Just happened 2 days ago.... i've tried reinstalling, different computers, resetting... 
I have ONE computer still logged in, and it works. I signed out of 2 computers and can't get back in, I don't want to sign out of that last computer and risk not being able to log in anymore. 

Does anyone know what is going on???

**Comment by Ash258** [comment] 2018-06-15 11:59
Duplicate of #1698

**Closed by Ash258** 2018-06-15 11:59 UTC
