### ISSUE TITLE
Feature/help request.

### ISSUE THREAD

**Issue by 613TheEvil** [saenzramiro/rambox#1174] opened 2017-09-21 17:18 UTC
Hi, forgive me but I am really new to github. I find Ramblox practical, even though the memory needed is too much for my poor old pc. I'd like to know how can I get a specific type of notification. Flashing the program in the toolbar is what works the best for me, now the program just changes its tray icon from white to red and sometimes shows message previews for a few weekends, but those require you to be paying attention on the screen at all times, not very practical. So, can I get the type of notification I want? It's what Skype does, to give you an idea. And if this is impossible in the current version, can I hope for it in a next one? Thanks for your time. Please move, edit this message as required.

**Comment by Ash258** [comment] 2018-07-08 16:53
Duplicate of #1155

**Closed by Ash258** 2018-07-08 16:53 UTC
