### ISSUE TITLE
ICON not show in Linux (Deepin 15.2 - Based Debian Unstable)

### ISSUE THREAD

**Issue by soycamiloypunto** [saenzramiro/rambox#134] opened 2016-07-21 20:00 UTC
![capturadeepin20160721145920](https://cloud.githubusercontent.com/assets/16060744/17036869/bf195b96-4f53-11e6-91cd-10fdd0fecadc.png)

Tray icon work perfect, but ICON MENU not working.

**Comment by saenzramiro** [comment] 2016-07-22 03:23
Thank you for your report @soycamiloypunto.

Duplicate of #94, please refer to that issue.

**Closed by saenzramiro** 2016-07-22 03:23 UTC
Labels: duplicate
