### ISSUE TITLE
Facebook Messenger High CPU Usage

### ISSUE THREAD

**Issue by thatgeek95** [saenzramiro/rambox#1248] opened 2017-10-19 01:52 UTC
Issue: The process from Rambox that contains the Facebook Messenger "tab" is using ~10% steadily despite not doing anything intensive (just sitting open idly). I know it is this specific process because when I kill it, the Messenger tab goes black but all other services work and CPU usage drops significantly. This is not a FB issue since the behavior is not exhibited in Chrome.

Steps to reproduce:

Open Rambox and be signed in to Facebook Messenger

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.13.7-1-ARCH

**Comment by op8867555** [comment] 2017-10-19 06:53
I can second this issue. The profiler shows it executes some idle callback repeatly.

![](https://i.imgur.com/nMD7cEL.png) (left: chromium 61.0.3163.100, right: rambox 0.5.13)

Version: 0.5.13
Platform: linux (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by berlinjunker** [comment] 2017-10-19 10:16
I can confirm this behaviour on my machine as well. CPU utilization drops from 25 percent to 1 when the fb-messenger tab is being deactivated.

Version: 0.5.13
Platform: MacOS 10.12.1
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by daimpi** [comment] 2017-10-19 14:09
I can confirm this on Windows 10 Pro (64-bit): With two logical (& physical) cores I get ~50% cpu usage in Task-Manager, suggesting that it's fully exhausting one core. And indeed, when binding Rambox to only one core, this core goes up to almost 100% usage. When minimizing Rambox, the load disappears after approx. 12 seconds and comes back as soon as the Rambox window is opened again. When using regular browsers (Chrome, Firefox) to access Facebook Messenger, this problem doesn't occur.

> Rambox 0.5.13
> Electron 1.7.8
> win32 x64 10.0.15063

**Comment by saenzramiro** [comment] 2017-10-19 18:39
@op8867555 Can you make the test again but instead of using Messenger service from Rambox, use Custom Service?

**Comment by op8867555** [comment] 2017-10-19 18:51
@saenzramiro 

Just tried using a custom service (url set to https://www.messenger.com) and it works well without issue. :)

![20171020-024456](https://user-images.githubusercontent.com/888716/31788256-c9a30464-b540-11e7-9b86-6489406bc4ad.png)

**Comment by daimpi** [comment] 2017-10-19 19:26
Update: I just noticed that the problem seems to be gone on my computer and I cannot reproduce it. I restarted my PC in the meantime and had temporarily added Messenger via the above custom URL, but now I'm back to the built-in Messenger and the problem isn't appearing there either… strange.

**Comment by rafalenden** [comment] 2017-10-19 19:52
I confirm the issue is gone, probably FB released a fix.

**Comment by saenzramiro** [comment] 2017-10-23 19:36
Great! So let's close this issue.

**Closed by saenzramiro** 2017-10-23 19:36 UTC
