### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by Akimace** [saenzramiro/rambox#1436] opened 2018-02-05 15:55 UTC
duplicate of #1386

**Comment by jacebenson** [comment] 2018-02-09 14:39
Did this issue start when you first started using the app, or did it start happening after you made some configuration changes?

**Comment by sxmanton** [comment] 2018-02-09 15:52
Hi, I also get this error. It seems to show up pretty consistently as long as I've left Rambox running for long enough (potentially computer locking/sleeping in between is also a factor). Once it crops up, it happens every time I get a notification, until I restart rambox and then everything is fine again, usually for a day or two.

**Comment by jsaalfeld** [comment] 2018-02-10 12:53
Is this a duplicate of #1386

**Closed** 2018-02-28 08:55 UTC
