### ISSUE TITLE
Services are defined, but they dont show up

### ISSUE THREAD

**Issue by artukrap** [saenzramiro/rambox#320] opened 2016-09-10 05:22 UTC
After version update from 0.4.1 to 0.4.2 my services are gone
[http://prntscr.com/cga5p6](http://prntscr.com/cga5p6)

-
> Rambox 0.4.2
> Electron 1.3.5
> win32 x64 10.0.14393

**Comment by brwolfgang** [comment] 2016-09-12 12:39
This is a duplicate of #313

**Comment by saenzramiro** [comment] 2016-09-12 23:02
@artukrap All your bugs are related. Please follow the steps I mentioned in the other issue.

**Closed by saenzramiro** 2016-09-12 23:02 UTC
