### ISSUE TITLE
When I double click on system tray icon, Rambox does not open.

### ISSUE THREAD

**Issue by gurolcay** [saenzramiro/rambox#942] opened 2017-06-14 07:11 UTC
1. Open Rambox and minimize Rambox
2. Double click system tray icon of Rambox, does not react

I think when I double click to Rambox icon at the system tray, it must be opened.

> Rambox: v0.5.9

> OS: Kubuntu 16.10 (KDE Plasma 5.8.5)

> Arch: linux (x64)

**Comment by edmundlaugasson** [comment] 2017-06-15 21:40
Looks like right click on systray icon and choose "Show/Hide Window" will do the trick.
Using:
Version: 0.5.9
Platform: linux (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by gurolcay** [comment] 2017-06-21 11:53
Yes, I am using "Show/Hide Window". Double clicking on the system tray icon makes it easier to right click on the system tray icon and select "Show / Hide Window".

**Comment by saenzramiro** [comment] 2017-07-30 16:16
We have to fix this, I will try to do it in next release.

**Comment by dbfin** [comment] 2017-08-22 22:40
I added another bug similar to this one, and it was commented to be a duplicate of this one. So I just closed it as a duplicate. And here is a brief copy of what I have and what I would like to see.

    Rambox: 0.5.10
    OS: Arch Linux
    Arch: x64
    KDE Plasma 5

- For me single/double clicking the icon does nothing.
- Right-clicking the icon and choosing Show/Hide Window works.
- In the code I see "double-click" event that is supposed to work. Maybe it does not on my system.
- Is it possible to add an option to preferences to choose single/double click on the icon to open Rambox? Or just change to single 'click' instead of 'double-click'? I suspect single clicking should work everywhere.

**Comment by dbfin** [comment] 2017-08-22 22:48
An additional question. What is the point of making it a double click? All other system tray icons I have (or had, such as Skype and Pidgin, for example) require a single click to open/close. Is there something different Rambox is supposed to do on single clicking (now or in the future)? Because in my case it does not do anything on a single click either.

**Comment by dbfin** [comment] 2017-09-07 21:29
It says that you "added this to the 0.5.11 milestone on Jul 30", just got 0.5.12, and still no go. Thanks.

**Comment by dbfin** [comment] 2017-09-07 23:48
@nmat I believe 'click' instead of 'double-click' should work on any platform. And that is a part of the suggestion, to show/hide it on a single click, rather than a double click.

**Comment by nmat** [comment] 2017-09-08 09:03
In that sense I do agree. Or have the option to change it in the preferences.

**Comment by wolframroesler** [comment] 2017-09-27 07:34
Got the same issue in Rambox 0.5.12 on Mint 18, Electron 1.7.5, libappindicator1 installed with apt. Left-clicking the tray icon does nothing, neither does left-double-clicking, have to right-click and select "Show/Hide Window".

**Comment by olivernight** [comment] 2017-09-27 12:16
Got some times the same issue on Windows 7

**Comment by saenzramiro** [comment] 2017-10-03 21:12
Like @nmat said, seems like `double-click` event is not supported in Linux, and `click` is supported only if `libappindicator` is not installed in the OS. I will change it to click in next release but it will depend on the user OS to work or not.

**Comment by dbfin** [comment] 2017-10-03 21:22
I believe this is the best way to address this issue, especially because single click is more consistent with the behavior of similar applications. But do you mean `click` is supported if `libappindicator` IS installed? Or you mean they conflict? Because this library is more or less standard. In any case, thanks for your work!

**Closed** 2017-10-04 21:01 UTC
Labels: bug

**Comment by wolframroesler** [comment] 2017-10-05 11:16
Opens on single click now (0.5.13). Thanks a lot for the quick help, that's a whole new experience!

**Comment by dbfin** [comment] 2017-10-05 22:20
@saenzramiro Just got v0.5.13. Indeed, when I now single click on the icon, it does open it, which is awesome. However, it does not close it back to the system tray if I click again. Not sure again what you meant by libappindicator above, but if that matters I have libappindicator-gtk3 (12.10.0-12) installed.
