### ISSUE TITLE
Can't login to Rambox account

### ISSUE THREAD

**Issue by Tuplad** [saenzramiro/rambox#1800] opened 2018-08-01 10:30 UTC
Version: 0.5.17
Platform: linux (x64)
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=17.1.11
DISTRIB_CODENAME=Hakoila
DISTRIB_DESCRIPTION="Manjaro Linux"
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

Changed language twice and found Rambox to be logged out of my account. Tried logging in but keep getting error that "something went wrong".

Password reset :+1: , still can't login.
Deleted cache, settings, /.config/rambox
Deleted rambox-bin and reinstalled again from stable repo (manjaro)
Still doen't work.

I can login with Google services though, but not with my account.

**Comment by Ash258** [comment] 2018-08-01 10:38
Duplicate of #1698

**Closed by Ash258** 2018-08-01 10:38 UTC
