### ISSUE TITLE
Javascript error in main process while changing to WhatsApp tab

### ISSUE THREAD

**Issue by jsanta** [saenzramiro/rambox#987] opened 2017-07-10 14:07 UTC
### Steps to reproduce

1. While changing to WhatsApp tab

### Expected behavior
Change without any errors or alerts.

### Actual behavior
![captura de pantalla 2017-07-10 a la s 10 01 42](https://user-images.githubusercontent.com/1641480/28021904-7b7f5f96-6557-11e7-8ae5-e0e8fac95cab.png)

```
**A JavaScript error occurred in the main process**
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 56998343682
    at updateBadge (/Applications/Rambox.app/Contents/Resources/app.asar/electron/main.js:264:7)
    at BrowserWindow.mainWindow.on (/Applications/Rambox.app/Contents/Resources/app.asar/electron/main.js:193:52)
    at emitTwo (events.js:106:13)
    at BrowserWindow.emit (events.js:194:7)
    at WebContents.webContents.on (/Applications/Rambox.app/Contents/Resources/electron.asar/browser/api/browser-window.js:81:10)
    at emitThree (events.js:116:13)
    at WebContents.emit (events.js:197:7)
```

### ENVIRONMENT

> Rambox Version: 0.5.10
Platform: darwin (x64)
Electron: 1.7.4
Chromium: 58.0.3029.110
Node: 7.9.0

> OS: macOS Sierra
> Arch: x64

**Comment by NotYannis** [comment] 2017-07-19 08:51
I got the same error on windows, when I receive a new message

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from C:\Users\Jean\AppData\Local\Rambox\app-0.5.9\resources\app.asar\resources\Icon.ico
    at Object.exports.setBadge (C:\Users\Jean\AppData\Local\Rambox\app-0.5.9\resources\app.asar\electron\tray.js:58:10)
    at updateBadge (C:\Users\Jean\AppData\Local\Rambox\app-0.5.9\resources\app.asar\electron\main.js:252:7)
    at BrowserWindow.mainWindow.on (C:\Users\Jean\AppData\Local\Rambox\app-0.5.9\resources\app.asar\electron\main.js:191:52)
    at emitTwo (events.js:106:13)
    at BrowserWindow.emit (events.js:194:7)
    at WebContents.webContents.on (C:\Users\Jean\AppData\Local\Rambox\app-0.5.9\resources\electron.asar\browser\api\browser-window.js:80:10)
    at emitThree (events.js:116:13)
    at WebContents.emit (events.js:197:7)

[OK]

**Comment by nmat** [comment] 2017-08-30 17:44
duplicate of: https://github.com/saenzramiro/rambox/issues/878

**Closed** 2018-04-25 22:20 UTC
