### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by 1beb** [saenzramiro/rambox#1456] opened 2018-02-15 16:19 UTC
On the download page, the link to the 64 bit .deb actually links to an archive file.

**Comment by mmoscher** [comment] 2018-02-23 07:45
Yep, can confirm :+1: 
Download leads to an tar.gz archiv

**Comment by AdrienHorgnies** [comment] 2018-03-08 09:10
I was about the open an issue to address this.

Hyperref link value is : `https://getrambox.herokuapp.com/download/linux_64?filetype=deb` but the file actually downloaded is `Rambox-0.5.16-x64.tar.gz`.

**Comment by Ash258** [comment] 2018-05-14 18:15
Duplicate of #1401

**Closed** 2018-05-14 18:16 UTC
