### ISSUE TITLE
iCloud Mail

### ISSUE THREAD

**Issue by gabryesse** [saenzramiro/rambox#494] opened 2016-11-29 17:09 UTC
Hi, when I try to log in into iCloud, it try to go into mailbox but return to the login form.

Thanks.

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by twinklebob** [comment] 2016-12-07 11:14
Duplicate of #405, which is still occurring for me on:

> Rambox 0.4.5
> Electron 1.4.7
> linux x64 3.19.0-32-generic

**Comment by saenzramiro** [comment] 2016-12-14 16:17
Ok, so let's close this issue.

**Closed by saenzramiro** 2016-12-14 16:17 UTC
Labels: investigate
