### ISSUE TITLE
Open a service as default on start

### ISSUE THREAD

**Issue by Mte90** [saenzramiro/rambox#957] opened 2017-06-20 10:57 UTC
Will be very comfortable to have a service as default as opened instead of the rambox page when I start Rambox.

**Comment by nmat** [comment] 2017-06-20 19:38
Sounds like a duplicate of: https://github.com/saenzramiro/rambox/issues/932

**Comment by Mte90** [comment] 2017-06-20 22:31
SImilar features indeed

**Comment by saenzramiro** [comment] 2017-08-15 18:31
We can add an option to open a default service or last one used.

**Closed** 2017-10-02 20:37 UTC
Labels: feature request
