### ISSUE TITLE
Global notification badge displays number contained in tab title

### ISSUE THREAD

**Issue by jadecdev** [saenzramiro/rambox#1120] opened 2017-09-04 14:30 UTC
### Steps to reproduce

1. Name a service "Slack12"
2. In the global notification badge, if I select "Slack12" tab, I see "12" in the notification badge instead of the real notification number

### Expected behavior
I see the right amount of notifications

### Actual behavior
I see a number that is in the tab title, nothing to do with the notification number

### ENVIRONMENT

> Rambox: 0.5.10
> OS: 10.12.6 (16G29)
> Arch: x64 

Examples with screenshots
<img width="455" alt="capture d ecran 2017-09-04 a 16 25 54" src="https://user-images.githubusercontent.com/13087581/30030572-3e294d1a-918e-11e7-88ac-7e86edba7ea3.png">
<img width="684" alt="capture d ecran 2017-09-04 a 16 28 26" src="https://user-images.githubusercontent.com/13087581/30030573-3e2f2212-918e-11e7-819c-9b7f1f916bf5.png">

**Comment by nmat** [comment] 2017-09-04 18:23
duplicate of https://github.com/saenzramiro/rambox/issues/1083

**Closed** 2018-05-16 23:05 UTC
