### ISSUE TITLE
Duplicated count of notifications in Rainloop service

### ISSUE THREAD

**Issue by marin-h** [saenzramiro/rambox#427] opened 2016-10-23 16:44 UTC
Whenever I get one and only one new e-mail I see number 2 standing in red in the notifications for Rainloop service. And when I get two e-mails I see number 4, and so on... 
Registered issue in GNOME desktop with Debian 8 stable and Ubuntu 16.04

## 

> Rambox 0.4.4
> Electron 1.4.1
> linux x64 3.16.0-4-amd64

**Comment by saenzramiro** [comment] 2016-10-24 12:46
Can you open the Developer Console of Rainloop and execute this code and share the results?

`var a=document.getElementsByClassName("badge pull-right count"),b=0;for(i=0;i<a.length;i++)parseInt(a[i].textContent.trim())%1===0&&(b+=parseInt(a[i].textContent.trim()));console.log('EMAIL COUNTER', b);`

To open Dev Console, right click in Rainloop tab.

**Comment by marin-h** [comment] 2016-10-25 18:14
Sorry for the delay, I am attaching the results.

Saludos :)

24 de octubre del 2016 9:46, "Ramiro Saenz"  escribió:
	Can you open the Developer Console of Rainloop and execute this code and share the results?

	var a=document.getElementsByClassName("badge pull-right count"),b=0;for(i=0;i

**Comment by saenzramiro** [comment] 2016-10-25 18:18
Nothing was attached. Please send it again.

**Comment by marin-h** [comment] 2016-10-26 19:43
Sorry, I don't know why the attachment failed. Here you go.

![captura de pantalla de 2016-10-26 16-42-04](https://cloud.githubusercontent.com/assets/5542756/19742378/2c8bd6ac-9b9b-11e6-97d6-cbd4959c6ba8.png)

**Comment by saenzramiro** [comment] 2016-10-27 00:12
Is there a possibility to have a temporal email in your host to debug the problem?

Because RainLoop demo is not enough to find the problem.

**Comment by marin-h** [comment] 2016-10-27 00:32
Yes, no problem. My email is marina @ staberman .com.ar

Saludos!

26 de octubre del 2016 21:12, "Ramiro Saenz"  escribió:
	Is there a possibility to have a temporal email in your host to debug the problem?

	Because RainLoop demo is not enough to find the problem.

**Comment by jsnfwlr** [comment] 2016-12-23 01:54
I have the same issue on my server - is anything else needed to debug this? I can provide a test account for anyone who wants to solve this problem

**Comment by Schnouki** [comment] 2017-02-13 14:25
Investigated a bit because I have the same issue. The problem is that there is some kind of hidden "wrapper" for the inbox that has the same count as the "regular" inbox. Therefore it is counted twice.

I did some testing and I believe it can be fixed by replacing `

    document.getElementsByClassName("badge pull-right count")

with

    document.querySelectorAll(".e-item .e-link:not(.hidden) .badge.pull-right.count")

I'll submit a PR.

**Comment by saenzramiro** [comment] 2017-02-18 02:05
Thank you @Schnouki!

**Closed** 2017-02-18 02:05 UTC
Labels: investigate
