### ISSUE TITLE
Gmail - can not add more than 3 accounts or incompatible with new login screen

### ISSUE THREAD

**Issue by AdKiller** [saenzramiro/rambox#832] opened 2017-05-01 18:43 UTC
### Steps to reproduce

1.  add more than 3 accounts
2.  can not enter user name and password on the 4th account because Gmail switches to new login screen and nothing can be clicked in the new version

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Windows 10 Pro 64bit  1607

> Arch: x64

**Comment by Saboteur777** [comment] 2017-05-02 07:23
The error is present with 2 accounts, too: the second one got logged out, now I can't log back in, so the problem is that "nothing can be clicked in the new version".

**Comment by irrenhaus** [comment] 2017-05-03 08:59
Another account, which I was able to log in, also says
`This version of Chrome is no longer supported. Please upgrade to asupported browser.`

Could be related to the new-login-screen problem.

**Comment by Saboteur777** [comment] 2017-05-03 10:13
Google might have fixed the login issue, now I can log in. 

The `This version of Chrome is no longer supported. Please upgrade to asupported browser.` message is quite old, I don't think it is relevant in this bug.

**Comment by Saboteur777** [comment] 2017-05-03 10:17
Opened a separate issue for the error message: https://github.com/saenzramiro/rambox/issues/837

**Comment by saenzramiro** [comment] 2017-06-07 16:49
Both problems are fixed in latest release.

**Closed by saenzramiro** 2017-06-07 16:49 UTC
