### ISSUE TITLE
ICQ notification not working

### ISSUE THREAD

**Issue by LiBOSS-CZ** [saenzramiro/rambox#1770] opened 2018-07-16 13:15 UTC
### Steps to reproduce

1. Add ICQ account 
2. Reciever message

### Expected behavior

Expected desktop notification and red blinking logo in system tray

### Actual behavior

No notification (just sound) and no logo change in system tray

### ENVIRONMENT

> Rambox: v0.5.17

> OS: Windows 10

> Arch: x64

Note: Javascript fix works - https://github.com/saenzramiro/rambox/issues/1702

**Comment by Ash258** [comment] 2018-07-16 16:14
So why do you create new issue if this issue is resolved with #1702 as you said?? 😕

**Comment by LiBOSS-CZ** [comment] 2018-07-16 16:38
First of all, I have found it after I create this issue and second it is still not corrected in the main code. Just workaround.

**Comment by Ash258** [comment] 2018-07-16 16:40
Duplicate of #1702

**Closed by Ash258** 2018-07-16 16:40 UTC
