### ISSUE TITLE
I can't hear sound in whatsapp

### ISSUE THREAD

**Issue by nicolangr** [saenzramiro/rambox#1668] opened 2018-05-24 15:45 UTC
When i play video or audo messages in whatsapp i can't hear sounds

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> linux x64 4.4.0-127-generic

**Comment by yafp** [comment] 2018-06-07 08:44
duplicate issue - see #1642

**Comment by Ash258** [comment] 2018-06-08 22:12
Duplicate of #1616

**Closed by Ash258** 2018-06-08 22:12 UTC
Labels: duplicate
