### ISSUE TITLE
deb 64 link redirects to .tar.gz file

### ISSUE THREAD

**Issue by Simon0Harms** [saenzramiro/rambox#1538] opened 2018-03-16 10:09 UTC
This link:
https://getrambox.herokuapp.com/download/linux_64?filetype=deb
redirects to the tar.gz file instead of the -x64.deb file

Same problem on this link:
https://getrambox.herokuapp.com/download/linux_32?filetype=deb

The links are on this site:
http://rambox.pro/#download

**Comment by Ash258** [comment] 2018-03-16 12:57
Duplicate of #1401

**Comment by Ash258** [comment] 2018-03-16 13:01
@Simon0Harms If you need debian package you can download it [here](https://github.com/saenzramiro/rambox/releases/download/0.5.16/Rambox_0.5.16-x64.deb)

**Closed** 2018-06-08 17:02 UTC
