### ISSUE TITLE
Memory leak in latest release

### ISSUE THREAD

**Issue by Stanzilla** [saenzramiro/rambox#868] opened 2017-05-19 17:05 UTC
Will try to diagnose this later, just wanted to get the report out, I have 3 services enabled, whatsapp, fb messenger and hangouts
![taskmgr_2017-05-19_19-01-12](https://cloud.githubusercontent.com/assets/75278/26258692/0ba196c6-3cc6-11e7-91df-52893824e5d1.png)

### Steps to reproduce

1. 
2. 
3. 

### ENVIRONMENT

> Rambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

**Comment by Stanzilla** [comment] 2017-05-19 20:46
It's the Hangouts tab, as soon as I enable hangouts, the memory goes off the roof

**Comment by anathemamask** [comment] 2017-05-20 05:01
Also experiencing this. Can confirm - hangouts tab is the cause. Verified in both 64 and 32 bit versions.

**Comment by piemonkey** [comment] 2017-05-20 11:35
I'm seeing what sounds like the same behaviour but in a Gmail tab. Version 0.5.8 on (Arch) Linux x64.

I'm seeing a Rambox process gradually increasing memory usage, for periods it seems to use 100% of a processor core, but at other times seems normal.

**Comment by JamesValero** [comment] 2017-05-20 13:25
I see this too on Mac (Sierra). Gmail won't even load. Already tried to create a new service but getting the same result.

**Comment by jbbr** [comment] 2017-05-20 23:38
Seems to be the same as #863 
I can confirm the bug. If I don't have GMail or Hangouts enabled but Whatsapp, Slack, Skype I don't have any problems - but once I add GMail and login, rambox eats all my RAM.

I did a memory snapshot - (heap+allocation profile&timeline). You can download it here (loadable in "memory" tab of devtools): https://s.jbbr.net/f/4797f350e7/?dl=1

Screenshots from devtool:
![heapsnapshot](https://cloud.githubusercontent.com/assets/682607/26280026/201bad84-3dc6-11e7-976e-7e51f9ca9d33.png)
![profile](https://cloud.githubusercontent.com/assets/682607/26280027/22892218-3dc6-11e7-9477-f50a868151e2.png)

**Comment by keplerk** [comment] 2017-05-21 00:29
Same here, I installed rambox in a new laptop and suddenly the amount of ram the process takes, goes to the roof.

**Comment by JamesValero** [comment] 2017-05-22 05:47
Anyone know how to get the previous version? I'm not finding an archived version list on the rambox.pro site.

**Comment by nmat** [comment] 2017-05-22 06:22
@JamesValero https://github.com/saenzramiro/rambox/releases

**Comment by M0UL** [comment] 2017-05-24 11:45
i am seeing this too. my rambox install was using more then 6 gb of ram.

**Comment by Pistashe** [comment] 2017-05-28 22:02
I am also experiencing this using Facebook Messenger. Whereas, Whatsapp of Slack are using less than 100 MB of RAM, Messenger is using around 1.5 GB even when it's running in the background.

**Comment by keplerk** [comment] 2017-05-28 22:51
I would recommend downgrade to the previous version until this is fixed.
Dunno when it will be.

**Comment by saenzramiro** [comment] 2017-05-30 14:24
Yes, this will be fixed in next release. Sorry guys.

The problem was caused because the javascript injection to get unread counter for Gmail and Hangouts.

New version will be released July 1st. ;)

**Closed by saenzramiro** 2017-05-30 14:24 UTC

**Comment by sxe** [comment] 2017-05-31 07:46
I hope you mean "June 1st". Otherwise i would suggest to push a hotfix release asp cause gmail and hangouts are way to important to let them stay like this for over a month.

**Comment by nmat** [comment] 2017-05-31 07:55
@sxe it is released already...check the releases on github

**Comment by sxe** [comment] 2017-05-31 08:18
hehe ok, the for the heads up.

**Comment by roizcorp** [comment] 2017-06-01 06:38
Sorry, I don't get it, 
Why close an issue if it is not fixed? keep it open for proper tracking

**Comment by kuteninja** [comment] 2017-06-01 08:41
There was another issue with the same error.

Have you checked version 0.5.9 yet?
It seems to be working just fine now.

**Comment by keplerk** [comment] 2017-06-01 13:32
Seems like now there is an annoying popup display for hangouts notifications when you receive a new message, popping up several notification windows until you read the message.

**Comment by roizcorp** [comment] 2017-06-01 14:19
I didn't even reported or noticed the issue, this is a purely development process question. 
Based on the answer that the defect will be fixed in July i.e. next version (greater than 0.5.9), I understand that this has not been fixed yet (I haven't found a matching commit for it). If all of the above is true, I think the proper time to close an issue is on verification that indeed the issue was fixed.
