### ISSUE TITLE
Slack Icons Missing again

### ISSUE THREAD

**Issue by bretterer** [saenzramiro/rambox#1771] opened 2018-07-16 15:07 UTC
Ever since upgrading a few versions ago, slack icons no longer load.

It has always been an issue for me that any slack teams over the 5th team also never loaded the icons.

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> darwin x64 17.6.0

**Comment by Ash258** [comment] 2018-07-16 16:15
Duplicate of #1408

**Closed by Ash258** 2018-07-16 16:15 UTC
