### ISSUE TITLE
cert problems with cloudfront, tumblr, etc. on Discord, Slack and VK (custom)

### ISSUE THREAD

**Issue by SimJoSt** [saenzramiro/rambox#577] opened 2017-01-15 22:39 UTC
Since a few days ago, I keep recurring messages, that some URLs have an invalid authority certification. The sites affected are *.cloudfront.net, ??.media.tumblr.com, *.mail.ru, counter.yadro.ru
I reloaded specific services to find the ones affected (Discord, Slack, VK.com) and then looked into the security tab on the developer tools, but I couldn't find anything but a non-https google tracking link.

These errors don't occur on my Chrome browser.

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by 1beb** [comment] 2017-01-15 23:39
Same here with *.cloudfront.net, ??.media.tumblr.com can't duplicate the other because I don't use VK

**Comment by scar45** [comment] 2017-01-16 00:09
Duplicate of #573

**Closed** 2017-01-22 17:41 UTC
