### ISSUE TITLE
Login, Password Reset and Sign Up not working anymore after using "fresh start"-function of Windows

### ISSUE THREAD

**Issue by punkrock** [saenzramiro/rambox#1687] opened 2018-06-01 17:01 UTC
Login worked fine, then I had to reset Windows using "[Windows Fresh Start](https://www.techrepublic.com/article/how-to-use-the-fresh-start-feature-in-windows-10-creators-update/)". Windows unistalled all programs and re-installed Windows, so you have a clean Windows. Then I re-installed Rambox and got the issue that I can't login, without getting an error (see "Actual behavior). Then I uninstalled Rambox manually, removed all Rambox-folders in /user/AppData/local and .../roaming. I also removed all registry entries. then I rebooted the machine and re-installed Rambox. Same issues. I can't login, can't reset the password or sign up.

### Steps to reproduce

Not possible as long as you don't have access to my machine.

### Expected behavior

Login, Password Reset and Sign Up should work.

### Actual behavior

Login: After giving my credentials and click the login button, the small login windows disappears and I am back in Rambox, but I am not logged in. No error message.

Password Reset: "WE'RE SORRY, SOMETHING WENT WRONG WHEN REQUESTING THE PASSWORD CHANGE."

Sign Up: "WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO SIGN UP."

### ENVIRONMENT

Windows 10 Pro x64, Version 1803, (Build 17134.81)

Version: 0.5.17
Platform: win32 (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

**Comment by Ash258** [comment] 2018-07-16 08:01
It has nothing to do with fresh start.
Duplicate of #1698

**Comment by Ash258** [comment] 2018-07-16 08:02
Duplicate of #1698

**Closed by Ash258** 2018-07-16 08:01 UTC
