### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by oliversalzburg** [saenzramiro/rambox#1753] opened 2018-07-03 10:24 UTC
### Steps to reproduce

No idea. This happens while I'm not actively using RamBox. I'm using WhatsApp, Facebook Messenger and Google Hangouts with it.

### Expected behavior

No error.

### Actual behavior

![image](https://user-images.githubusercontent.com/1658949/42214455-e07b363a-7ebb-11e8-98e8-433ff4b6cd0d.png)

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from C:\Users\OliverSalzburg\AppData\Local\Rambox\app-0.5.17\resources\app.asar\resources\IconTrayUnread.ico
    at Object.exports.setBadge (C:\Users\OliverSalzburg\AppData\Local\Rambox\app-0.5.17\resources\app.asar\electron\tray.js:76:10)
    at updateBadge (C:\Users\OliverSalzburg\AppData\Local\Rambox\app-0.5.17\resources\app.asar\electron\main.js:282:7)
    at BrowserWindow.mainWindow.on (C:\Users\OliverSalzburg\AppData\Local\Rambox\app-0.5.17\resources\app.asar\electron\main.js:219:52)
    at emitTwo (events.js:125:13)
    at BrowserWindow.emit (events.js:213:7)
    at WebContents.webContents.on (C:\Users\OliverSalzburg\AppData\Local\Rambox\app-0.5.17\resources\electron.asar\browser\api\browser-window.js:82:10)
    at emitThree (events.js:135:13)
    at WebContents.emit (events.js:216:7)

[OK]
```

### ENVIRONMENT

> Rambox: v0.5.17

> OS: Windows 10

> Arch: x64

**Comment by Ash258** [comment] 2018-07-03 10:36
Duplicate of #1656

**Closed by Ash258** 2018-07-03 10:36 UTC
