### ISSUE TITLE
No audio from any service being played, MacOS

### ISSUE THREAD

**Issue by hknoener** [saenzramiro/rambox#1792] opened 2018-07-27 06:32 UTC
My Rambox was working fine until last night. There was no update, I have not changed anything on my Hardware/Software overnight. Out of the blue, the sound for all my channels stopped working. I can't hear anything from audio messages, videos, anything. 

Already tried to reinstall and the problem persists.

### ENVIRONMENT

Rambox: 0.5.17
Platform: Darwin (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1
OS: MacOS High Sierra (10.13.6)

**Comment by Ash258** [comment] 2018-07-27 13:46
Check if do not disturb mode in Rambox is enabled. (F1 key shortcut / rambox dashboard has its icon)

**Comment by hknoener** [comment] 2018-07-27 13:56
@Ash258 This is basically the first instruction we have in every single ticket about this problem. All this to say that this was my first step. 

Of course, the fact that I haven't touched anything about it also helps.

**Comment by Ash258** [comment] 2018-07-27 14:03
So you already tested something and didnt write what you tested already?? 

Nothing special / specifying to be separate issue.

**Comment by Ash258** [comment] 2018-07-27 14:03
Duplicate of #1425

**Closed by Ash258** 2018-07-27 14:03 UTC

**Comment by hknoener** [comment] 2018-07-27 20:42
Ok, @Ash258, let's see.

> So you already tested something and didnt write what you tested already??
Well, if you want to consider it a test, yeah, I'm guilty. 

Other than...
- Being on a different version of Rambox
- Being on a different OS
- Being on a different Electron version
... and, on top of that being a different problem...

> There is **no sound playing video** at any applications

> I can't hear anything from audio messages, videos, anything.

... you are right, there's nothing special or specific about this issue.

Maybe you also want to close #1739, #1492, #1329, #1287, and maybe even #1253.
