### ISSUE TITLE
Add Quasselweb support pls

### ISSUE THREAD

**Issue by alien2003** [saenzramiro/rambox#1077] opened 2017-08-19 18:17 UTC
https://github.com/magne4000/quassel-webserver

There is stil no way to IRC from Rambox but IRC is one of the most popular messaging services.

**Comment by johannesgunnar** [comment] 2017-08-31 12:14
Note that Rambox both supports IRCCloud and Kiwi IRC so it is possible to IRC from Rambox

**Comment by alien2003** [comment] 2017-09-01 14:21
Thank you. I'll try Kiwi IRC because IRCCloud is not secure

**Comment by rodneyrod** [comment] 2017-09-30 04:53
Found out that this is fixed in a yet to be merged pull request

magne4000/quassel-webserver#240

**Comment by Ash258** [comment] 2018-06-08 22:57
Duplicate of #704

**Closed by Ash258** 2018-06-08 22:57 UTC
