### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by Gaafgeel** [saenzramiro/rambox#1795] opened 2018-07-30 12:50 UTC
When switching tabs (Telegram, Whatsapp, etc), sometimes this error pops up

![image](https://user-images.githubusercontent.com/25752041/43398044-2c2f80bc-9407-11e8-8b48-c0df1223687d.png)

Version: 0.5.17
Platform: win32(x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

**Comment by Ash258** [comment] 2018-07-30 16:00
Duplicate of #1656

**Closed by Ash258** 2018-07-30 16:00 UTC
