### ISSUE TITLE
Badge counter for WhatsApp

### ISSUE THREAD

**Issue by idstone** [saenzramiro/rambox#1446] opened 2018-02-11 23:35 UTC
Hi...  is something wrong again with badge counter for WhatsApp?

	-
	> Rambox 0.5.14
	> Electron 1.7.8
	> darwin x64 16.7.0

**Comment by captain-o** [comment] 2018-02-12 12:09
I get push notifications for New WhatsApp messages but they are not mentioned in the counter on the task line symbol.


Version: 0.5.14
Platform: win32 (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by idstone** [comment] 2018-02-12 12:56
Yes, that's it captain-o ... same here

**Comment by Stanzilla** [comment] 2018-02-12 14:55
Same here, guess their recent update changed something. @saenzramiro

**Comment by LurchiStromberg** [comment] 2018-02-12 23:07
HI!
At Franz Messenger its fixed already!

Here whats the Issuse:

> 
because of a whatsapp update (obfuscated class names) the unread messages selector had to be updated. this is fixed now and the hotfix will be pushed soon to all clients! 
>

**Comment by brunorsini** [comment] 2018-02-12 23:54
+1, also really miss a working Whatsapp counter!

**Comment by Ash258** [comment] 2018-02-13 14:48
Try to add custom javascript code:

```javascript
function checkUnread() {
	const elements = document.querySelectorAll('.CxUIE, .unread');
	let count = 0;

	for (let i = 0; i < elements.length; i += 1) {
		if (elements[i].querySelectorAll('*[data-icon="muted"]').length === 0) {
			count += 1;
		}
	}
	
	updateBadge(count)
}
function updateBadge(count) {
	if (count && count >= 1) {
		rambox.setUnreadCount(count);
	} else {
		rambox.clearUnreadCount();
	}
}

setInterval(checkUnread, 1e3);
```
Cannot test it now. Give me feedback if its fix issue.

**Comment by maki-chan** [comment] 2018-02-14 19:19
@Ash258 This workaround does work and that's great for now in my case.

**Comment by maki-chan** [comment] 2018-02-14 20:21
Yes, it is. Rambox shows the correct unread messages counter.

**Comment by LurchiStromberg** [comment] 2018-02-14 21:00
@Ash258 
So when you think Rambox Update will be available?

**Comment by brunorsini** [comment] 2018-02-14 21:07
+1 to this working on Whatsapp + 0.5.14. Thanks for the fix!

**Comment by LurchiStromberg** [comment] 2018-02-14 23:04
As I started Whats App at Rambox there been a Message, that Whats App making an Update...

But still same Issue, new / unread Messages not shown in Bagde at Windows Version

**Comment by LurchiStromberg** [comment] 2018-02-15 16:58
Okay, tried 4 Times to install Rambox new....Whats app is still not working on current 64 Bit Windows Version.
Changed back to Franz at what whats app works again like a charme...

**Comment by Ash258** [comment] 2018-02-15 19:43
@LurchiStromberg Of course its not working after clean install. Noone accept PR and release new version of Rambox. There is temporary solution in few comments above. Thats all.

**Comment by LurchiStromberg** [comment] 2018-02-15 21:33
Ah okay...
So some guys shouldnt write here its fixed in 0.5.14...
Its messing!

**Comment by LurchiStromberg** [comment] 2018-02-15 23:43
oh gosh, i was standing on the wire, sorry...
Now i got it working too :)

**Comment by orschiro** [comment] 2018-02-16 17:02
@Ash258 your code is working greatly! Now it shows the icon red. :-)

But doesn't show a count of unread right?

![image](https://user-images.githubusercontent.com/170947/36319541-81769a8c-1343-11e8-80e9-7cbe73428097.png)

**Comment by Ash258** [comment] 2018-02-16 17:13
Tray icon isn't showing number. (at least on Windows). But you can see global unread counter in window title and service tab.
![Title](https://image.prntscr.com/image/AP6SW_OPTS2rHS3jEslMPA.png "Title, services")

**Comment by orschiro** [comment] 2018-02-16 17:16
True, sufficient for now. Thanks!

**Comment by Darkein** [comment] 2018-02-23 14:46
The fix works for me, but the badge is flickering. Anyway, it's better than nothing. Thanks :)

**Comment by saenzramiro** [comment] 2018-02-26 14:26
I will release a fix for this ASAP.

**Closed** 2018-02-26 14:40 UTC

**Comment by Darkein** [comment] 2018-03-05 13:14
The problem is fixed for me since the last upade, thanks

**Comment by perryloh** [comment] 2018-03-27 01:14
I think this might not be working again in 0.5.16. Anyone else experiencing similar behaviour ?

**Comment by orschiro** [comment] 2018-03-27 07:34
For me it's still working on Fedora 27.

```
Version: 0.5.16
Platform: linux (x64)
Electron: 1.8.3
Chromium: 59.0.3071.115
Node: 8.2.1
```
