### ISSUE TITLE
Gmail won't show unread counter on tab

### ISSUE THREAD

**Issue by magicdave1** [saenzramiro/rambox#1720] opened 2018-06-15 18:54 UTC
-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.17134

**Comment by idarktech** [comment] 2018-06-15 21:32
I am also experiencing this problem. New GMAIL does not show the unread counter on the tab.

**Comment by Ash258** [comment] 2018-06-15 21:46
Duplicate of #1659 already PR in #1661

**Closed by Ash258** 2018-06-15 21:46 UTC
