### ISSUE TITLE
Repeated issue: slack unread count

### ISSUE THREAD

**Issue by dare023** [saenzramiro/rambox#1150] opened 2017-09-13 07:19 UTC
After latest update slack was clearing unread messages, but stopped again.
Let me know if you need anything from me.
Arch Linux, latest Rambox
Thank you

**Comment by dmetzler1988** [comment] 2017-09-13 07:37
On one client the same problem occurs (macOS Sierra). 
We had install rambox again and it works perfectly. 
@dare023 Can you maybe try to reinstall rambox and check again?

**Comment by dare023** [comment] 2017-09-13 08:33
Actually, I just deleted Rambox folder from ~.config/.
Seems to work now.
@dmetzler1988 thank you for a hint.

**Comment by Mte90** [comment] 2017-09-18 10:29
I can confirm happen very often and the refresh is not helpful.
I cannot delete my rambox configuration (I have 6 chat configured) so someone has other suggestions?

**Comment by jcherniak** [comment] 2017-09-19 03:28
I'm also seeing the channel icon pop up frequently on different Slack installs.  Any ideas?

**Comment by dmetzler1988** [comment] 2017-09-19 07:13
@Mte90 can you maybe sync/backup your rambox configuration? After sync you can remove the config and restore the backup.

**Comment by Mte90** [comment] 2017-09-19 09:40
But I cannot do that every day or everytime happen using rambox.

**Comment by dare023** [comment] 2017-09-19 09:41
I did it once and seem to work fine until now.
Guess it is try and see?

**Comment by Mte90** [comment] 2017-09-19 09:55
I renamed the folder of Rambox, open rambox, close, remove the new folder, rename the old one and now seems working.
Very strange (I discovered to have 1.4gb of config folder o.0)

**Comment by Mte90** [comment] 2017-09-19 14:28
After a while the problem happen again so is not only a problem of settings folder, maybe something in the memory that is not resetted

**Comment by dmetzler1988** [comment] 2017-09-19 14:35
maybe try to reinstall?
on mac simple move the *.app file over the existing one in application folder and overwrite it (this solved the problem on the mac of a friend)

**Comment by Mte90** [comment] 2017-09-19 14:38
I am using linux but for me there is a bug because sometimes the notification count remain in other case doesn't.

**Comment by parabolic** [comment] 2017-09-20 10:40
:+1: Same here. I've got many chats I really do not feel like removing the .config folder.

**Comment by dare023** [comment] 2017-09-25 07:17
Ok, it is back for me again. 
Guess will need to learn to live with that, as I cant reset all every few days.
Hope will be fixed soon.

**Comment by jcherniak** [comment] 2017-09-25 10:22
I have a feeling this is related to #1175.  Until that's merged, you can copy/paste the revised update code into the custom JS field for Slack.  It fixed it for me at least.

**Comment by Mte90** [comment] 2017-10-05 08:21
seems fixed with the latest release

**Closed** 2018-06-08 22:56 UTC
