### ISSUE TITLE
Not support Socks proxy

### ISSUE THREAD

**Issue by skyfire000** [saenzramiro/rambox#1628] opened 2018-05-02 08:50 UTC
I use a socks proxy , however , the rambox only supports http proxy.

	
	-
	> Rambox 0.5.15
	> Electron 1.8.2
	> win32 x64 10.0.17133

**Comment by Ash258** [comment] 2018-05-02 11:07
Duplicate of #740

**Closed** 2018-05-17 23:14 UTC
Labels: duplicate
