### ISSUE TITLE
Outlook Web App mailbox can not be added as a service

### ISSUE THREAD

**Issue by theunsfvo** [saenzramiro/rambox#345] opened 2016-09-16 08:32 UTC
Hi, I'm accessing an Outlook account via the web app (Version: 14.3.248.2) through an exchange service. I get the following error:

Server Error
401 - Unauthorized: Access is denied due to invalid credentials.
You do not have permission to view this directory or page using the credentials that you supplied.

### Steps to reproduce

1. add custom service
2. enter url
3. receive error screen

### ENVIRONMENT

> Rambox: v0.4.2

> OS: Win 10 Pro

> Arch: x64

**Comment by saenzramiro** [comment] 2016-09-18 02:36
Can you access via Google Chrome?

**Comment by theunsfvo** [comment] 2016-09-19 06:37
Yes, that is where I always use it, but it pops up with a domain like logon
screen where I must enter my network credentials.

Regards,
Theuns  - "I love deadlines. I like the whooshing sound they make as they
fly by." Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *
   My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>

**Comment by Mentis** [comment] 2016-09-28 18:47
Probably Rambox does not support "basic authentication". 

I have similar issue with my outlook365 which redirects to company login page. Then page should popup basic auth dialog where I can add credentials however nothing happen in rambox :(

**Comment by saenzramiro** [comment] 2016-09-28 23:55
@Mentis Thank you for that explanation, now understood the problem.

I just created an issue for this #378, so I will work on that in a future release.

I will close this issue because is not a bug and I just created a feature issue.

**Closed by saenzramiro** 2016-09-28 23:55 UTC
