### ISSUE TITLE
There's no spelling correction in slack

### ISSUE THREAD

**Issue by matanshel** [saenzramiro/rambox#1513] opened 2018-03-06 07:31 UTC
-
	> Rambox 0.5.15
	> Electron 1.8.2
	> darwin x64 17.4.0

**Comment by PackElend** [comment] 2018-06-10 15:57
would like too see it too

**Comment by Ash258** [comment] 2018-06-10 18:04
I think it should be duplicate of #509. Right?

**Comment by PackElend** [comment] 2018-06-10 18:06
it is

**Comment by Ash258** [comment] 2018-06-10 18:20
Duplicate of #509

**Closed by Ash258** 2018-06-10 18:20 UTC
