### ISSUE TITLE
RAMBOX BUG AGAIN AND AGAIN

### ISSUE THREAD

**Issue by Iblort** [saenzramiro/rambox#1742] opened 2018-06-29 08:13 UTC
![untitled-3](https://user-images.githubusercontent.com/40687567/42081154-0665deca-7b85-11e8-8b69-4f6023efd860.jpg)

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.17134

**Comment by Arebs** [comment] 2018-06-29 10:00
As Iblort don't provide Information to reproduce it, I will do it instead: 
It usually happens if you have opened Rambox for a while (1 day or more usually). This Error message popped then up every time you switch to another chat.  If you restart Rambox, the Error is gone. 

	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.16299

**Comment by Iblort** [comment] 2018-06-29 10:07
I cannot agree... this does not disappear when I restart Rambox. I NEED TO RESTART WHOLE COMPUTER. That is the reason why it is so bad and disappointing.

**Comment by Ash258** [comment] 2018-06-29 11:12
Duplicate of #1656

**Closed by Ash258** 2018-06-29 11:12 UTC

**Comment by nniesen** [comment] 2018-07-05 15:23
> I cannot agree... this does not disappear when I restart Rambox. I NEED TO RESTART WHOLE COMPUTER. That is the reason why it is so bad and disappointing.

You have to do "File >Quit Rambox", otherwise you're not restarting it because it's still running in the System Tray.
