### ISSUE TITLE
Microsoft Teams Browser Version Isn't Supported

### ISSUE THREAD

**Issue by vadriewyn** [saenzramiro/rambox#1364] opened 2017-12-18 01:49 UTC
Opening up Microsoft Teams from Rambox now shows an error with the browser not being supported. I'm not sure what the built-in browser for Rambox is, but in the event it's using related to the system's default browser, I have ensured that all my installed browsers (Internet Explorer, Microsoft Edge, Chrome, Firefox) are at their latest versions as well.

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.16299

**Comment by luispintomartins** [comment] 2017-12-18 11:41
+1 

	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.10.0-42-generic

**Comment by 0xCCD** [comment] 2017-12-18 15:10
+1

**Comment by pbek** [comment] 2017-12-20 06:36
Thank you for this wonderful software!

Same on KDE Neon

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.4.0-103-generic

**Comment by pbek** [comment] 2017-12-20 06:39
Office365 still works

**Comment by kepalas** [comment] 2017-12-21 07:04
+1

**Comment by chicojasl** [comment] 2017-12-21 15:10
This worked for me: https://github.com/saenzramiro/rambox/issues/1354#issuecomment-350966660

**Comment by AKFourSeven** [comment] 2017-12-26 09:00
@chicojasl I can confirm this fix works on macOS Sierra, albeit a bit slow, but better than nothing.

**Comment by saenzramiro** [comment] 2017-12-26 17:34
Duplicate of #1354. Let's merge it.

**Closed by saenzramiro** 2017-12-26 17:34 UTC
