### ISSUE TITLE
Are you going to integrate the new Google Hangout (Google Chat) ? 

### ISSUE THREAD

**Issue by Nacer-BKRM** [saenzramiro/rambox#1604] opened 2018-04-19 09:33 UTC
There is a client app for the moment but it's redirecting to web page 
https://gsuite.google.com/products/chat/

### Steps to reproduce

1. 
2. 
3. 

### ENVIRONMENT

> Rambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

**Comment by Ash258** [comment] 2018-04-19 12:38
Duplicate of #1502 
Already PR in #1572

**Comment by Nacer-BKRM** [comment] 2018-04-19 13:42
Thank you for the quick reply ! 
Hope you will find a solution soon 👍 :) 

Something strange, the google application redirects me to a chrome webpage.

**Comment by saenzramiro** [comment] 2018-04-25 21:59
Yes, in next version will be there. ;)

**Closed by saenzramiro** 2018-04-25 21:59 UTC
