### ISSUE TITLE
Microsoft teams

### ISSUE THREAD

**Issue by areal060781** [saenzramiro/rambox#881] opened 2017-05-26 13:55 UTC
I got a blue screen when I sign in my microsoft teams account...

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-78-generic

**Comment by nmat** [comment] 2017-05-26 16:00
Hello,

The microsoft teams sign in is fixed in upcoming release of 0.5.8 (next release)

**Comment by nmat** [comment] 2017-05-30 08:22
@saenzramiro this is fixed in 0.5.8/.9?

duplicate of: https://github.com/saenzramiro/rambox/issues/859

**Comment by nmat** [comment] 2017-05-31 08:27
I tested this with rambox 0.5.9 and it works flawless here. Please give it another run to see if you can login.

**Comment by saenzramiro** [comment] 2017-06-13 17:53
@nmat Yes, it's fixed in v0.5.9.

**Closed by saenzramiro** 2017-06-13 17:53 UTC
