### ISSUE TITLE
White bar on the bottom of Rambox in Slack

### ISSUE THREAD

**Issue by zurbergram** [saenzramiro/rambox#815] opened 2017-04-19 15:10 UTC
There is a white bar at the bottom of the rambox window when viewing a Slack team on Linux Mint 18, see attached image.  I have tried restarting Rambox and resizing window issue didn't go away.

![image](https://cloud.githubusercontent.com/assets/1094999/25187273/8c9f7970-24f0-11e7-800c-69421bed8d38.png)

RELEASE=18
CODENAME=sarah
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 18 Sarah"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_sarah_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_sarah_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 18 Cinnamon 64-bit

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-72-generic

**Comment by saenzramiro** [comment] 2017-04-21 20:36
Did you try to open Dev Tools and inspect that bar?

You can do it by right-click in tab service and select Dev Tools.

**Comment by forteller** [comment] 2017-04-23 10:48
FWIW I don't have that in Ubuntu Gnome 16.10.

**Comment by aidenlangley** [comment] 2017-04-24 01:56
Consistently experience this here as well - muted channels and "All Unreads" in Slack.

![rambox_2017-04-24_13-55-19](https://cloud.githubusercontent.com/assets/684721/25319839/c08ef4aa-28f5-11e7-8cf3-1682115a6100.png)

Version: 0.5.3
Platform: win32 (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by zurbergram** [comment] 2017-04-24 12:42
When selecting the white space it goes to the body tag.
I added a height: 100% to the client-ui div and the white space went away.  It appears that for some reason the client-ui div is not using the max height available

**Comment by aidenlangley** [comment] 2017-04-24 13:08
I can't change a thing here. Even if that is the solution, I don't want to implement it myself.

**Comment by gossi** [comment] 2017-04-25 11:32
Same for me. If you do hover the blue sidebar on the left (maybe sometimes the lover left, where there is actually is white), then it shows the contents for the white bar. I wonder if this may also be a problem of slack and not just rambox?

**Comment by saenzramiro** [comment] 2017-04-25 18:09
Any help with this will be appreciated. =S

**Comment by ignasg** [comment] 2017-04-26 10:35
Reproduced on windows chrome 32 bit Version 53.0.2785.116 64 seems to be ok

**Comment by petro-rudenko** [comment] 2017-04-27 09:40
Reproduced on OS X Sierra.

**Comment by nmat** [comment] 2017-04-28 08:43
Can't reproduce this on windows 10 64bit

**Comment by gossi** [comment] 2017-04-29 16:51
I pinged slack about it (I wrote their help team and let them know about this issue).

AND I realized it might only appear on channels which are muted. I think, that if you unmute a channel, the white bar is gone and if you mute it again, the white bar appears. Can you confirm this?

**Comment by petro-rudenko** [comment] 2017-05-01 10:01
Confirm that unmuting channel makes white bar to disappear.

**Comment by zurbergram** [comment] 2017-05-01 13:54
Confirmed as well

**Comment by adamwoodnz** [comment] 2017-05-03 23:20
Also happens on 'All Unreads' which is not mutable

**Comment by mrv777** [comment] 2017-05-10 13:28
I can confirm this issue on OSX 10.11.6 on muted channels in Slack

**Comment by NgoHuy** [comment] 2017-05-23 03:48
I can confirm, unmuted is workaround

**Comment by adamwoodnz** [comment] 2017-05-23 03:52
Not a workaround for 'All unread'. Adding `.client-ui { height: 100% }` in devtools works

**Comment by gossi** [comment] 2017-05-23 13:46
It is solved for me. My guess is, slack devs had a look at it. What about you guys?

**Comment by adamwoodnz** [comment] 2017-05-23 20:44
Nope. No change to Slack CSS when I inspect it. Doesn't happen when viewing in Chrome OSX.

**Comment by petro-rudenko** [comment] 2017-05-24 13:19
Same for me. Still a white bar on the muted channels at the bottom.

**Comment by saenzramiro** [comment] 2017-06-07 19:00
Seems like is a Slack bug, so I will close this thread for now.

**Closed by saenzramiro** 2017-06-07 19:00 UTC
