### ISSUE TITLE
Use icon of Slack/RocketChat

### ISSUE THREAD

**Issue by Mte90** [saenzramiro/rambox#955] opened 2017-06-20 10:42 UTC
On Slack and Rocketchat you can configure the icon to reconize very easily the chat but actually there is only the official icon of the service itself.

**Comment by jamy015** [comment] 2017-06-20 17:44
Duplicate of #113 (except that one is only about Slack)

**Comment by saenzramiro** [comment] 2017-08-15 18:25
We will add this in a future release.

Let's merge with #113

**Closed by saenzramiro** 2017-08-15 18:25 UTC
