### ISSUE TITLE
Please add CTRL-F to search

### ISSUE THREAD

**Issue by Cyph3r** [saenzramiro/rambox#1027] opened 2017-07-27 04:01 UTC
CTRL-F to search does not work.

### Steps to reproduce

1.  CTRL-F
2.  Nothing happens
3.  Profit. oh wait, actually no...

### Expected behavior

Backend is built on a tabbed browser. Should search the text of the currently active tab and frame.

### Actual behavior

Nothing. The screen just stares back at you.

### ENVIRONMENT

> Rambox: v0.5.10

> OS: Windows 10

> Arch: x64 or ia32
x64

**Comment by gingerbeardman** [comment] 2017-07-27 15:39
+1

**Comment by DylanVanAssche** [comment] 2017-07-31 17:23
+1

**Comment by HoracePGreeley** [comment] 2017-08-12 11:33
+1

**Comment by JoeyKhd** [comment] 2017-08-15 07:04
+1

**Comment by poisonborz** [comment] 2017-08-23 09:11
+1

**Comment by cwerner1** [comment] 2017-08-23 13:44
+1

**Comment by i-give-up** [comment] 2018-03-21 23:46
Same as https://github.com/saenzramiro/rambox/issues/242

**Comment by Cyph3r** [comment] 2018-03-21 23:48
Please implement...

**Comment by gingerbeardman** [comment] 2018-03-21 23:54
Use Station or Franz

**Comment by Cyph3r** [comment] 2018-03-22 00:18
@gingerbeardman I don't like Franz, but I hadn't heard of Station. Wow, thanks for that tip! Loving it already and am switching everything over right now.

If you have any other hot new software to recommend, hit me up.

**Comment by Ash258** [comment] 2018-05-17 23:11
Duplicate of #242

**Closed by Ash258** 2018-05-17 23:11 UTC
Labels: duplicate
