### ISSUE TITLE
(Double-)Clicking the Tray Icon Not Working

### ISSUE THREAD

**Issue by dbfin** [saenzramiro/rambox#1082] opened 2017-08-22 00:12 UTC
### Steps to reproduce

1. Run Rambox in Arch Linux (KDE Plasma 5 in my case).
2. Make sure the tray icon is shown by checking the corresponding box in settings. 
3. Close Rambox to the icon. Click or double-click the icon.

### Expected behavior

Rambox opens.

### Actual behavior

It does not. Nothing happens (whether Rambox is open or closed to the icon).

### ENVIRONMENT

> Rambox: 0.5.10

> OS: Arch Linux

> Arch: x64

> Plasma 5

**Comment by dbfin** [comment] 2017-08-22 00:16
Just in case: right-clicking the icon and choosing Show/Hide Window works.

Investigation: In the code I see "double-click" event that is supposed to work. Maybe it does not on my system.

A possible solution: add an option to preferences to choose single/double click on the icon to open Rambox.

**Comment by nmat** [comment] 2017-08-22 05:40
Duplicate of: https://github.com/saenzramiro/rambox/issues/942

**Closed** 2017-08-22 22:34 UTC
