### ISSUE TITLE
Rambox no longer supports MS Teams due to browswer incompatability

### ISSUE THREAD

**Issue by leonteale** [saenzramiro/rambox#1358] opened 2017-12-14 14:06 UTC
### Steps to reproduce

Add TEAMS into rambox

### Expected behavior

Loads teams web interface
### Actual behavior

unsupported version (one of the only reason I use rambox for work now)

### ENVIRONMENT

Linux (Kali) x64

**Comment by Ash258** [comment] 2017-12-14 21:45
Duplicate of #1354

**Closed** 2017-12-18 12:44 UTC
