### ISSUE TITLE
Cannot Command+F to find text

### ISSUE THREAD

**Issue by ukazap** [saenzramiro/rambox#1650] opened 2018-05-11 03:03 UTC
I'm trying to find text in tab, naturally I assume I can with Command+F like most other apps in macOS.

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> darwin x64 16.6.0

**Comment by Ash258** [comment] 2018-05-11 10:47
Duplicate of #1027

**Closed** 2018-05-17 23:09 UTC
Labels: duplicate
