### ISSUE TITLE
Yahoo mail : Cant bypass upgrade browser screen

### ISSUE THREAD

**Issue by procyyon** [saenzramiro/rambox#1054] opened 2017-08-08 06:59 UTC
Rambox 0.5.10 

Clicking on "try it later" nothing happens (windows 10 x64 & Linux Mint 18.2 x64).

**Comment by aravindhp** [comment] 2017-08-10 17:47
Duplicate of #833

**Comment by Canis-Enigmas** [comment] 2017-08-19 12:28
It is a duplicate, but it is now a different situation. 
Yahoo seems to have updated their site code and the "Try it later" bypass button does not work any more. All of my Yahoo! accounts are now dead in Rambox!

**Comment by saenzramiro** [comment] 2017-08-29 13:50
@Canis-Enigmas Ok, but let's continue this in #833.

**Closed by saenzramiro** 2017-08-29 13:50 UTC
