### ISSUE TITLE
Opening link in Office 365 opens 19 tabs

### ISSUE THREAD

**Issue by thejoycekung** [saenzramiro/rambox#81] opened 2016-07-09 00:51 UTC
I know there was a similar issue with multiple tabs being opened when links in Gmail, Inbox etc were clicked, but that was fixed - this is still ongoing for some reason.

**Comment by saenzramiro** [comment] 2016-07-09 23:03
Thank you @thejoycekung for the report, but the issue is related because is a bug for handling all links in webviews. So I marked as fixed but it will be fixed in next release. #6 #28 #19 

So stay tunned to update. :wink:

**Closed by saenzramiro** 2016-07-09 23:03 UTC
Labels: duplicate
