### ISSUE TITLE
Signal - Open Whisper Systems

### ISSUE THREAD

**Issue by JeroenBoersma** [saenzramiro/rambox#737] opened 2017-03-15 08:30 UTC
As Signal is gaining users it would be nice to have it in Rambox

https://www.whispersystems.org/

**Comment by JeroenBoersma** [comment] 2017-03-15 08:37
Ah, I see #26 #268

**Comment by JeroenBoersma** [comment] 2017-03-15 08:38
Still I think I would be great re-start the discussion...

**Comment by saenzramiro** [comment] 2017-04-03 17:10
What you propose? Because Signal still don't have any web app accessible via URL. :cry:

**Comment by vauvenal5** [comment] 2017-04-07 11:16
Well there is a Chrome app for Signal. If I am not mistaken, Chromium is somewhere under to hood, isn't it? So basically there should be a way to enable Signal installation as a plugin.

**Comment by saenzramiro** [comment] 2017-04-07 21:13
Yes, Rambox use Electron, and Electron use Chromium. But Electron is not supporting extensions and they don't have plans to do it.

The idea of Rambox is not have services inside the code, so we will always load services remotely. We will have to wait to Signal's team to release a web app.

**Comment by bjo81** [comment] 2017-05-27 21:07
But https://github.com/diracdeltas/signal-muon is also build on electron.

**Comment by saenzramiro** [comment] 2017-05-30 14:26
@bjo81 Is not Electron, that uses Muon. Is like Electron with the feature that you can install extentions, so they installed the signal extention in it.

**Comment by queicherius** [comment] 2017-11-01 01:07
Looks like the [new version of signal desktop](https://github.com/WhisperSystems/Signal-Desktop) uses "basic" electron, possibly this opens the discussion back up?

**Comment by fuelflo** [comment] 2017-11-01 13:02
+1

**Comment by ruiumbelino** [comment] 2017-11-02 11:23
+1

**Comment by saenzramiro** [comment] 2017-12-14 14:08
Lets continue this in #26

**Comment by Ash258** [comment] 2018-05-16 23:00
Duplicate of #26

**Closed by Ash258** 2018-05-16 23:00 UTC
