### ISSUE TITLE
Synchronization fails after X time

### ISSUE THREAD

**Issue by gabriele-lamon** [saenzramiro/rambox#656] opened 2017-02-01 08:35 UTC
Hi,
this morning I got the add about th no more automatic sync of configurations, so i started it manually and I got this error:

There was an error getting the profile: 401: Unauthorized

and now there are no more services registered...

### Steps to reproduce

1. go to your name menù
2. Synchronize Configuration
3. Restore

### Expected behavior

All my previous services restored

### Actual behavior

error getting the profile: 401: Unauthorized
and lost all registered services

### ENVIRONMENT

> Rambox: v0.5.3

> OS: win32 (x64)

> Arch: x64

thank you,
Gabriele.

**Comment by Litueros** [comment] 2017-02-03 09:40
I have the same problem with the same error message. I can't synchronize, restore or backup my Rambox account.

Thank you
Litueros

**Comment by saenzramiro** [comment] 2017-02-07 12:23
Yes, I noticed that too.

The problem is because the session is expired so I cannot synchronize. I will fix this in next release.

**Comment by dmetzler1988** [comment] 2017-03-02 14:55
same problem with restore and backup.
hope this will be fixed in the next days ;)

**Comment by Litueros** [comment] 2017-03-02 17:17
Thanks for the info. I hope the result. 

    El Jueves 2 de marzo de 2017 15:55, Daniel Metzler <notifications@github.com> escribió:
 

 same problem with restore and backup.
hope this will be fixed in the next days ;)—

**Comment by adamwoodnz** [comment] 2017-03-14 08:31
👍

**Comment by dmetzler1988** [comment] 2017-03-23 09:54
@saenzramiro maybe for future:
make little releases for bugs like this, because it's a bug and not a feature - and bugs should be solved as fast as you can and often can't wait same months. 
Maybe one release a week in which you only solve bugs. Or every two weeks.  
Only as an idea for future processing ;)

**Comment by saenzramiro** [comment] 2017-04-03 19:07
@dmetzlet1988 Of course I would like to release most often but I don't have time and Rambox donations are not enough for my food. Hopefully in a future this will change and I can dedicate my days to Rambox. :wink:

**Comment by Caf** [comment] 2017-04-08 00:18
That bug is indeed VERY annoying. ;)

**Closed** 2017-05-19 03:04 UTC
Labels: bug
